#!/bin/bash

# Define the API Url for pikachu
API_URL="https://pokeapi.co/api/v2/pokemon/pikachu"

# Make API request and save in data.json
curl -s -f "$API_URL" -o data.json

# Check if the command is successful
if [ $? -ne 0 ]; then
    echo "[$(date)] Error fetching pikachu data from $API_URL" >> errors.txt
else
    echo "Pikachu data saved to data.json"
fi